import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useQuery} from "@apollo/client";
import {GET_CLASSES} from "../graphql/queries";


const Home: NextPage = () => {
    const { loading, error, data} = useQuery(GET_CLASSES)
    if (loading) return <p>Loading...</p>
    if (error) return <p>Error :(</p>
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        <meta name="viewport" content="minimum-scale=1, initial-scale=1, width=device-width"/>
      </Head>

      <main className={styles.main}>
          <div>{ data.classes.map((classs: any) => (<strong key={classs.id}>{classs.title}</strong>))}</div>
        </main>
    </div>
  )
}

export default Home
